name: build

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  run-tests:
    runs-on: [self-hosted]
    steps:
      - name: Check out Code
        uses: actions/checkout@main
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main